[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.build]
cmds = ["npm ci", "npx prisma generate", "npm run build"]

[start]
cmd = "npx prisma migrate deploy && npm start -- -p ${PORT:-3000}"
